language: php

php:
  - 7.2
  - 7.3.24
  - 7.4

install:
  - printf "\n" | pecl install yaml
  - travis_retry composer require --no-update "php-coveralls/php-coveralls:^1 | ^2"
  - composer self-update
  - composer install --dev --no-interaction

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml