language: php

php:
  - 7.2
  - 7.3
  - 7.4

before_script:
  - sudo pecl install yaml

install:
  - composer self-update
  - composer install --dev --no-interaction

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml